// Generated by gencpp from file xtlidar_ros/ControlResponse.msg
// DO NOT EDIT!


#ifndef XTLIDAR_ROS_MESSAGE_CONTROLRESPONSE_H
#define XTLIDAR_ROS_MESSAGE_CONTROLRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace xtlidar_ros
{
template <class ContainerAllocator>
struct ControlResponse_
{
  typedef ControlResponse_<ContainerAllocator> Type;

  ControlResponse_()
    {
    }
  ControlResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::xtlidar_ros::ControlResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::xtlidar_ros::ControlResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlResponse_

typedef ::xtlidar_ros::ControlResponse_<std::allocator<void> > ControlResponse;

typedef boost::shared_ptr< ::xtlidar_ros::ControlResponse > ControlResponsePtr;
typedef boost::shared_ptr< ::xtlidar_ros::ControlResponse const> ControlResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::xtlidar_ros::ControlResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace xtlidar_ros

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::xtlidar_ros::ControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::xtlidar_ros::ControlResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::xtlidar_ros::ControlResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::xtlidar_ros::ControlResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "xtlidar_ros/ControlResponse";
  }

  static const char* value(const ::xtlidar_ros::ControlResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::xtlidar_ros::ControlResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::xtlidar_ros::ControlResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::xtlidar_ros::ControlResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // XTLIDAR_ROS_MESSAGE_CONTROLRESPONSE_H
