#代价地图官方说明：http://wiki.ros.org/costmap_2d

#全局代价地图参数命名空间
global_costmap:
  #代价地图的TF坐标系
  global_frame: map 
  #机器人的TF坐标名称
  robot_base_frame: base_footprint

  #上述TF坐标转换停止发布多长时间，控制机器人停止，单位：s
  transform_tolerance: 1

  #代价地图刷新频率，单位：Hz
  update_frequency: 1.5
  #代价地图的可视化话题发布频率，单位：Hz
  publish_frequency: 1.0

  #是否直接使用map_server提供的静态地图生成代价地图，没有使用参数设置为false
  #使用plugins手动配置代价地图时，该参数无效
  #static_map: true  

  #代价地图是否跟随机器人移动，static_map为true时该参数必须为false
  rolling_window: false
  #代价地图宽度，单位：m
  width: 10.0 
  #代价地图高度，单位：m
  height: 10.0 
  #代价地图分辨率（米/单元格）
  resolution: 0.05
  
  #代价地图设置地图层，包含静态层、障碍层和膨胀层
  #注意障碍层使用VoxelLayer代替ObstacleLayer
  #参数以地图层名称作为命名空间，在costmap_common_params.yaml文件设置  
  plugins:
    - {name: static_layer,      type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,    type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,   type: "costmap_2d::InflationLayer"}