## *********************************************************
##
## File autogenerated for the opencv_apps package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'name': 'Default', 'type': '', 'state': True, 'cstate': 'true', 'id': 0, 'parent': 0, 'parameters': [{'name': 'use_camera_info', 'type': 'bool', 'default': False, 'level': 0, 'description': 'Indicates that the camera_info topic should be subscribed to to get the default input_frame_id. Otherwise the frame from the image message will be used.', 'min': False, 'max': True, 'srcline': 291, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'edit_method': '', 'ctype': 'bool', 'cconsttype': 'const bool'}, {'name': 'pyramids_type', 'type': 'int', 'default': 0, 'level': 0, 'description': 'Pyramids Type', 'min': 0, 'max': 2, 'srcline': 291, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'edit_method': "{'enum': [{'name': 'Up', 'type': 'int', 'value': 0, 'srcline': 10, 'srcfile': '/home/nuc_1/TarkBot/src/tarkbot_demo/opencv_apps/cfg/Pyramids.cfg', 'description': 'Zoom In', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'Down', 'type': 'int', 'value': 1, 'srcline': 11, 'srcfile': '/home/nuc_1/TarkBot/src/tarkbot_demo/opencv_apps/cfg/Pyramids.cfg', 'description': 'Zoom Out', 'ctype': 'int', 'cconsttype': 'const int'}], 'enum_description': 'An enum for Pyramids Types'}", 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'num_of_pyramids', 'type': 'int', 'default': 1, 'level': 0, 'description': 'Number of pyramids', 'min': 1, 'max': 10, 'srcline': 291, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'edit_method': '', 'ctype': 'int', 'cconsttype': 'const int'}], 'groups': [], 'srcline': 246, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py', 'class': 'DEFAULT', 'parentclass': '', 'parentname': 'Default', 'field': 'default', 'upper': 'DEFAULT', 'lower': 'groups'}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

Pyramids_Up = 0
Pyramids_Down = 1
